### ISSUE TITLE
Request to Add Background Assets to the Repository

### ISSUE THREAD

**Issue by jeanfrontiers** [myssal/BrownDust2-Spine#1]
First of all, I would like to express my gratitude for the work you've done in sharing assets for BD2 in this repository. The resources provided here are very useful to understand how they "distribute" the images.

I am reaching out to request if it's possible to include the background and scenery assets (images of the various environments and locations featured in the game). These assets would be good for enthusiasts who are studying or working on similar projects.

Thank you for considering my request.

Best regards,

**Comment by myssal** [comment]
Sorry for late reply. 
For you request, i'll push them to the repo on next update.
And no, that's not how they organized or "distribute" their internal assets, i have to sort them manually.

**Comment by jeanfrontiers** [comment]
Thank you very much for fulfilling my request!
